CREATE DATABASE IF NOT EXISTS LSG_NBA
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

CREATE TABLE FRANQUICIA (
    codi INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(30) NOT NULL UNIQUE,
    ciutat VARCHAR(30) NOT NULL,
    ZonaGeografica VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE DRAFT_JUGADOR_FRANQUICIA (
    codi INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    any INT(4) NOT NULL,
    codi_franquicia INT UNSIGNED NOT NULL,
    FOREIGN KEY (codi_franquicia) REFERENCES FRANQUICIA(codi) 
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PERSONA (
    codi INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(30) NOT NULL,
    cognom VARCHAR(30) NOT NULL,
    DNI CHAR(9) NOT NULL UNIQUE,
    Sexe ENUM('H', 'D', 'NB', 'ND') NOT NULL,
    data_naixement DATE NOT NULL
);

CREATE TABLE PRODUCTE (
    codi INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(30) NOT NULL,
    preu DECIMAL(10,2) NOT NULL,
    quantitat INT UNSIGNED NOT NULL
);

CREATE TABLE TREBALLADOR (
    codi INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sou DECIMAL(10,2) NOT NULL,
    codi_persona INT UNSIGNED NOT NULL,
    FOREIGN KEY (codi_persona) REFERENCES PERSONA(codi) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMPRA (
    codi INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codi_producte INT UNSIGNED NOT NULL,
    codi_persona INT UNSIGNED NOT NULL,
    quantitat INT UNSIGNED NOT NULL,
    cost DECIMAL(10,2) NOT NULL,
    data_compra DATE NOT NULL,
    FOREIGN KEY (codi_producte) REFERENCES PRODUCTE(codi) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (codi_persona) REFERENCES PERSONA(codi) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PARTIT (
    codi INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    data_partit DATE NOT NULL,
    codi_franquicia_local INT UNSIGNED NOT NULL,
    codi_franquicia_visitant INT UNSIGNED NOT NULL,
    Es_guanyador BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (codi_franquicia_local) REFERENCES FRANQUICIA(codi) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (codi_franquicia_visitant) REFERENCES FRANQUICIA(codi) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

